// Mocks generated by Mockito 5.4.4 from annotations
// in fitmix_pwa/test/qa/T15_log_detail_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitmix_pwa/data/exercise_library_repo.dart' as _i6;
import 'package:fitmix_pwa/data/session_repo.dart' as _i2;
import 'package:fitmix_pwa/models/session.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SessionRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepo extends _i1.Mock implements _i2.SessionRepo {
  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String ymd(DateTime? d) => (super.noSuchMethod(
        Invocation.method(
          #ymd,
          [d],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #ymd,
            [d],
          ),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #ymd,
            [d],
          ),
        ),
      ) as String);

  @override
  DateTime ymdToDateTime(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #ymdToDateTime,
          [ymd],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #ymdToDateTime,
            [ymd],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.method(
            #ymdToDateTime,
            [ymd],
          ),
        ),
      ) as DateTime);

  @override
  _i3.Future<_i5.Session?> get(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [ymd],
        ),
        returnValue: _i3.Future<_i5.Session?>.value(),
        returnValueForMissingStub: _i3.Future<_i5.Session?>.value(),
      ) as _i3.Future<_i5.Session?>);

  @override
  _i3.Future<void> put(_i5.Session? s) => (super.noSuchMethod(
        Invocation.method(
          #put,
          [s],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [ymd],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markRest(
    String? ymd, {
    required bool? rest,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRest,
          [ymd],
          {#rest: rest},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> copyDay({
    required String? fromYmd,
    required String? toYmd,
    List<int>? pickIndexes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyDay,
          [],
          {
            #fromYmd: fromYmd,
            #toYmd: toYmd,
            #pickIndexes: pickIndexes,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Session>> getSessionsInRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionsInRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<List<_i5.Session>>.value(<_i5.Session>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.Session>>.value(<_i5.Session>[]),
      ) as _i3.Future<List<_i5.Session>>);

  @override
  _i3.Future<List<_i5.Session>> getWorkoutSessions() => (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSessions,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Session>>.value(<_i5.Session>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.Session>>.value(<_i5.Session>[]),
      ) as _i3.Future<List<_i5.Session>>);

  @override
  _i3.Future<Set<String>> getAllWorkoutDates() => (super.noSuchMethod(
        Invocation.method(
          #getAllWorkoutDates,
          [],
        ),
        returnValue: _i3.Future<Set<String>>.value(<String>{}),
        returnValueForMissingStub: _i3.Future<Set<String>>.value(<String>{}),
      ) as _i3.Future<Set<String>>);

  @override
  _i3.Future<Set<String>> getAllRestDates() => (super.noSuchMethod(
        Invocation.method(
          #getAllRestDates,
          [],
        ),
        returnValue: _i3.Future<Set<String>>.value(<String>{}),
        returnValueForMissingStub: _i3.Future<Set<String>>.value(<String>{}),
      ) as _i3.Future<Set<String>>);

  @override
  _i3.Future<({Set<String> restDates, Set<String> workoutDates})>
      getAllSessionDates() => (super.noSuchMethod(
            Invocation.method(
              #getAllSessionDates,
              [],
            ),
            returnValue: _i3.Future<
                ({
                  Set<String> restDates,
                  Set<String> workoutDates
                })>.value((restDates: <String>{}, workoutDates: <String>{})),
            returnValueForMissingStub: _i3.Future<
                ({
                  Set<String> restDates,
                  Set<String> workoutDates
                })>.value((restDates: <String>{}, workoutDates: <String>{})),
          ) as _i3.Future<({Set<String> restDates, Set<String> workoutDates})>);

  @override
  _i3.Future<List<_i2.ExerciseHistoryRecord>> getRecentExerciseHistory(
    String? exerciseName, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentExerciseHistory,
          [exerciseName],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i2.ExerciseHistoryRecord>>.value(
            <_i2.ExerciseHistoryRecord>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i2.ExerciseHistoryRecord>>.value(
                <_i2.ExerciseHistoryRecord>[]),
      ) as _i3.Future<List<_i2.ExerciseHistoryRecord>>);

  @override
  _i3.Future<void> seedDummyWorkoutData() => (super.noSuchMethod(
        Invocation.method(
          #seedDummyWorkoutData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ExerciseLibraryRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseLibraryRepo extends _i1.Mock
    implements _i6.ExerciseLibraryRepo {
  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, List<String>>> getLibrary() => (super.noSuchMethod(
        Invocation.method(
          #getLibrary,
          [],
        ),
        returnValue: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
        returnValueForMissingStub: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i3.Future<Map<String, List<String>>>);

  @override
  _i3.Future<void> addExercise(
    String? bodyPart,
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExercise,
          [
            bodyPart,
            exerciseName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateExercise(
    String? oldBodyPart,
    String? oldExerciseName,
    String? newBodyPart,
    String? newExerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [
            oldBodyPart,
            oldExerciseName,
            newBodyPart,
            newExerciseName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteExercise(
    String? bodyPart,
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [
            bodyPart,
            exerciseName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
