// Mocks generated by Mockito 5.4.4 from annotations
// in fitmix_pwa/test/features/qa_session_04_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitmix_pwa/data/auth_repo.dart' as _i15;
import 'package:fitmix_pwa/data/exercise_library_repo.dart' as _i7;
import 'package:fitmix_pwa/data/routine_repo.dart' as _i10;
import 'package:fitmix_pwa/data/session_repo.dart' as _i3;
import 'package:fitmix_pwa/data/settings_repo.dart' as _i13;
import 'package:fitmix_pwa/data/user_repo.dart' as _i8;
import 'package:fitmix_pwa/models/routine.dart' as _i11;
import 'package:fitmix_pwa/models/session.dart' as _i6;
import 'package:fitmix_pwa/models/user_profile.dart' as _i9;
import 'package:flutter/foundation.dart' as _i2;
import 'package:flutter/material.dart' as _i14;
import 'package:google_sign_in/google_sign_in.dart' as _i16;
import 'package:hive_flutter/hive_flutter.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueListenable_1<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SessionRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepo extends _i1.Mock implements _i3.SessionRepo {
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String ymd(DateTime? d) => (super.noSuchMethod(
        Invocation.method(
          #ymd,
          [d],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #ymd,
            [d],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #ymd,
            [d],
          ),
        ),
      ) as String);

  @override
  DateTime ymdToDateTime(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #ymdToDateTime,
          [ymd],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #ymdToDateTime,
            [ymd],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.method(
            #ymdToDateTime,
            [ymd],
          ),
        ),
      ) as DateTime);

  @override
  _i4.Future<_i6.Session?> get(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [ymd],
        ),
        returnValue: _i4.Future<_i6.Session?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.Session?>.value(),
      ) as _i4.Future<_i6.Session?>);

  @override
  _i4.Future<void> put(_i6.Session? s) => (super.noSuchMethod(
        Invocation.method(
          #put,
          [s],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [ymd],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markRest(
    String? ymd, {
    required bool? rest,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRest,
          [ymd],
          {#rest: rest},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> copyDay({
    required String? fromYmd,
    required String? toYmd,
    List<int>? pickIndexes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyDay,
          [],
          {
            #fromYmd: fromYmd,
            #toYmd: toYmd,
            #pickIndexes: pickIndexes,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Session>> getSessionsInRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionsInRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i6.Session>>.value(<_i6.Session>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.Session>>.value(<_i6.Session>[]),
      ) as _i4.Future<List<_i6.Session>>);

  @override
  _i4.Future<List<_i6.Session>> getWorkoutSessions() => (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSessions,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Session>>.value(<_i6.Session>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.Session>>.value(<_i6.Session>[]),
      ) as _i4.Future<List<_i6.Session>>);

  @override
  _i4.Future<Set<String>> getAllWorkoutDates() => (super.noSuchMethod(
        Invocation.method(
          #getAllWorkoutDates,
          [],
        ),
        returnValue: _i4.Future<Set<String>>.value(<String>{}),
        returnValueForMissingStub: _i4.Future<Set<String>>.value(<String>{}),
      ) as _i4.Future<Set<String>>);

  @override
  _i4.Future<Set<String>> getAllRestDates() => (super.noSuchMethod(
        Invocation.method(
          #getAllRestDates,
          [],
        ),
        returnValue: _i4.Future<Set<String>>.value(<String>{}),
        returnValueForMissingStub: _i4.Future<Set<String>>.value(<String>{}),
      ) as _i4.Future<Set<String>>);

  @override
  _i4.Future<List<_i3.ExerciseHistoryRecord>> getRecentExerciseHistory(
    String? exerciseName, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentExerciseHistory,
          [exerciseName],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i3.ExerciseHistoryRecord>>.value(
            <_i3.ExerciseHistoryRecord>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i3.ExerciseHistoryRecord>>.value(
                <_i3.ExerciseHistoryRecord>[]),
      ) as _i4.Future<List<_i3.ExerciseHistoryRecord>>);

  @override
  _i4.Future<void> seedDummyWorkoutData() => (super.noSuchMethod(
        Invocation.method(
          #seedDummyWorkoutData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ExerciseLibraryRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseLibraryRepo extends _i1.Mock
    implements _i7.ExerciseLibraryRepo {
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, List<String>>> getLibrary() => (super.noSuchMethod(
        Invocation.method(
          #getLibrary,
          [],
        ),
        returnValue: _i4.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
        returnValueForMissingStub: _i4.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i4.Future<Map<String, List<String>>>);

  @override
  _i4.Future<void> addExercise(
    String? bodyPart,
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExercise,
          [
            bodyPart,
            exerciseName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateExercise(
    String? oldBodyPart,
    String? oldExerciseName,
    String? newBodyPart,
    String? newExerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [
            oldBodyPart,
            oldExerciseName,
            newBodyPart,
            newExerciseName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteExercise(
    String? bodyPart,
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [
            bodyPart,
            exerciseName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UserRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepo extends _i1.Mock implements _i8.UserRepo {
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i9.UserProfile?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i4.Future<_i9.UserProfile?>.value(),
        returnValueForMissingStub: _i4.Future<_i9.UserProfile?>.value(),
      ) as _i4.Future<_i9.UserProfile?>);

  @override
  _i4.Future<void> saveUserProfile(_i9.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [profile],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [RoutineRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutineRepo extends _i1.Mock implements _i10.RoutineRepo {
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i11.Routine>> listAll() => (super.noSuchMethod(
        Invocation.method(
          #listAll,
          [],
        ),
        returnValue: _i4.Future<List<_i11.Routine>>.value(<_i11.Routine>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i11.Routine>>.value(<_i11.Routine>[]),
      ) as _i4.Future<List<_i11.Routine>>);

  @override
  _i4.Future<_i11.Routine?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i4.Future<_i11.Routine?>.value(),
        returnValueForMissingStub: _i4.Future<_i11.Routine?>.value(),
      ) as _i4.Future<_i11.Routine?>);

  @override
  _i4.Future<void> save(_i11.Routine? routine) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [routine],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLastUsed(String? id) => (super.noSuchMethod(
        Invocation.method(
          #updateLastUsed,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.ValueListenable<_i12.Box<_i11.Routine>> listenable() =>
      (super.noSuchMethod(
        Invocation.method(
          #listenable,
          [],
        ),
        returnValue: _FakeValueListenable_1<_i12.Box<_i11.Routine>>(
          this,
          Invocation.method(
            #listenable,
            [],
          ),
        ),
        returnValueForMissingStub:
            _FakeValueListenable_1<_i12.Box<_i11.Routine>>(
          this,
          Invocation.method(
            #listenable,
            [],
          ),
        ),
      ) as _i2.ValueListenable<_i12.Box<_i11.Routine>>);
}

/// A class which mocks [SettingsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepo extends _i1.Mock implements _i13.SettingsRepo {
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i14.ThemeMode> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i4.Future<_i14.ThemeMode>.value(_i14.ThemeMode.system),
        returnValueForMissingStub:
            _i4.Future<_i14.ThemeMode>.value(_i14.ThemeMode.system),
      ) as _i4.Future<_i14.ThemeMode>);

  @override
  _i4.Future<void> saveThemeMode(_i14.ThemeMode? themeMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveThemeMode,
          [themeMode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isOnboardingComplete() => (super.noSuchMethod(
        Invocation.method(
          #isOnboardingComplete,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> setOnboardingComplete(bool? complete) => (super.noSuchMethod(
        Invocation.method(
          #setOnboardingComplete,
          [complete],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i15.AuthRepo {
  @override
  _i4.Future<_i16.GoogleSignInAccount?> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i4.Future<_i16.GoogleSignInAccount?>.value(),
        returnValueForMissingStub:
            _i4.Future<_i16.GoogleSignInAccount?>.value(),
      ) as _i4.Future<_i16.GoogleSignInAccount?>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
