// Mocks generated by Mockito 5.4.4 from annotations
// in fitmix_pwa/test/features/session_07_qa_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitmix_pwa/data/exercise_library_repo.dart' as _i12;
import 'package:fitmix_pwa/data/routine_repo.dart' as _i7;
import 'package:fitmix_pwa/data/session_repo.dart' as _i3;
import 'package:fitmix_pwa/data/user_repo.dart' as _i10;
import 'package:fitmix_pwa/models/routine.dart' as _i8;
import 'package:fitmix_pwa/models/session.dart' as _i6;
import 'package:fitmix_pwa/models/user_profile.dart' as _i11;
import 'package:flutter/foundation.dart' as _i2;
import 'package:hive_flutter/hive_flutter.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueListenable_1<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SessionRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepo extends _i1.Mock implements _i3.SessionRepo {
  MockSessionRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String ymd(DateTime? d) => (super.noSuchMethod(
        Invocation.method(
          #ymd,
          [d],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #ymd,
            [d],
          ),
        ),
      ) as String);

  @override
  DateTime ymdToDateTime(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #ymdToDateTime,
          [ymd],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #ymdToDateTime,
            [ymd],
          ),
        ),
      ) as DateTime);

  @override
  _i4.Future<_i6.Session?> get(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [ymd],
        ),
        returnValue: _i4.Future<_i6.Session?>.value(),
      ) as _i4.Future<_i6.Session?>);

  @override
  _i4.Future<void> put(_i6.Session? s) => (super.noSuchMethod(
        Invocation.method(
          #put,
          [s],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [ymd],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Session>> listAll() => (super.noSuchMethod(
        Invocation.method(
          #listAll,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Session>>.value(<_i6.Session>[]),
      ) as _i4.Future<List<_i6.Session>>);

  @override
  _i4.Future<void> markRest(
    String? ymd, {
    required bool? rest,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRest,
          [ymd],
          {#rest: rest},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> copyDay({
    required String? fromYmd,
    required String? toYmd,
    List<int>? pickIndexes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyDay,
          [],
          {
            #fromYmd: fromYmd,
            #toYmd: toYmd,
            #pickIndexes: pickIndexes,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Session>> getSessionsInRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionsInRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i6.Session>>.value(<_i6.Session>[]),
      ) as _i4.Future<List<_i6.Session>>);

  @override
  _i4.Future<List<_i6.Session>> getWorkoutSessions() => (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSessions,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Session>>.value(<_i6.Session>[]),
      ) as _i4.Future<List<_i6.Session>>);

  @override
  _i4.Future<List<_i3.ExerciseHistoryRecord>> getRecentExerciseHistory(
    String? exerciseName, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentExerciseHistory,
          [exerciseName],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i3.ExerciseHistoryRecord>>.value(
            <_i3.ExerciseHistoryRecord>[]),
      ) as _i4.Future<List<_i3.ExerciseHistoryRecord>>);

  @override
  _i4.Future<void> seedDummyWorkoutData() => (super.noSuchMethod(
        Invocation.method(
          #seedDummyWorkoutData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [RoutineRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutineRepo extends _i1.Mock implements _i7.RoutineRepo {
  MockRoutineRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.Routine>> listAll() => (super.noSuchMethod(
        Invocation.method(
          #listAll,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Routine>>.value(<_i8.Routine>[]),
      ) as _i4.Future<List<_i8.Routine>>);

  @override
  _i4.Future<_i8.Routine?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i4.Future<_i8.Routine?>.value(),
      ) as _i4.Future<_i8.Routine?>);

  @override
  _i4.Future<void> save(_i8.Routine? routine) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [routine],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLastUsed(String? id) => (super.noSuchMethod(
        Invocation.method(
          #updateLastUsed,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.ValueListenable<_i9.Box<_i8.Routine>> listenable() => (super.noSuchMethod(
        Invocation.method(
          #listenable,
          [],
        ),
        returnValue: _FakeValueListenable_1<_i9.Box<_i8.Routine>>(
          this,
          Invocation.method(
            #listenable,
            [],
          ),
        ),
      ) as _i2.ValueListenable<_i9.Box<_i8.Routine>>);
}

/// A class which mocks [UserRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepo extends _i1.Mock implements _i10.UserRepo {
  MockUserRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i11.UserProfile?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i4.Future<_i11.UserProfile?>.value(),
      ) as _i4.Future<_i11.UserProfile?>);

  @override
  _i4.Future<void> saveUserProfile(_i11.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [profile],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ExerciseLibraryRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseLibraryRepo extends _i1.Mock
    implements _i12.ExerciseLibraryRepo {
  MockExerciseLibraryRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, List<String>>> getLibrary() => (super.noSuchMethod(
        Invocation.method(
          #getLibrary,
          [],
        ),
        returnValue: _i4.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i4.Future<Map<String, List<String>>>);

  @override
  _i4.Future<void> addExercise(
    String? bodyPart,
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExercise,
          [
            bodyPart,
            exerciseName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateExercise(
    String? oldBodyPart,
    String? oldExerciseName,
    String? newBodyPart,
    String? newExerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [
            oldBodyPart,
            oldExerciseName,
            newBodyPart,
            newExerciseName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteExercise(
    String? bodyPart,
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [
            bodyPart,
            exerciseName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
