// Mocks generated by Mockito 5.4.4 from annotations
// in fitmix_pwa/test/features/t05_empty_session_save_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitmix_pwa/data/exercise_library_repo.dart' as _i6;
import 'package:fitmix_pwa/data/session_repo.dart' as _i2;
import 'package:fitmix_pwa/models/session.dart' as _i5;
import 'package:hive_flutter/hive_flutter.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SessionRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepo extends _i1.Mock implements _i2.SessionRepo {
  MockSessionRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String ymd(DateTime? d) => (super.noSuchMethod(
        Invocation.method(
          #ymd,
          [d],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #ymd,
            [d],
          ),
        ),
      ) as String);

  @override
  DateTime ymdToDateTime(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #ymdToDateTime,
          [ymd],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #ymdToDateTime,
            [ymd],
          ),
        ),
      ) as DateTime);

  @override
  _i3.Future<_i5.Session?> get(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [ymd],
        ),
        returnValue: _i3.Future<_i5.Session?>.value(),
      ) as _i3.Future<_i5.Session?>);

  @override
  _i3.Future<void> put(_i5.Session? s) => (super.noSuchMethod(
        Invocation.method(
          #put,
          [s],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? ymd) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [ymd],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Session>> listAll() => (super.noSuchMethod(
        Invocation.method(
          #listAll,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Session>>.value(<_i5.Session>[]),
      ) as _i3.Future<List<_i5.Session>>);

  @override
  _i3.Future<void> markRest(
    String? ymd, {
    required bool? rest,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRest,
          [ymd],
          {#rest: rest},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> copyDay({
    required String? fromYmd,
    required String? toYmd,
    List<int>? pickIndexes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyDay,
          [],
          {
            #fromYmd: fromYmd,
            #toYmd: toYmd,
            #pickIndexes: pickIndexes,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Session>> getSessionsInRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionsInRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<List<_i5.Session>>.value(<_i5.Session>[]),
      ) as _i3.Future<List<_i5.Session>>);

  @override
  _i3.Future<List<_i5.Session>> getWorkoutSessions() => (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSessions,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Session>>.value(<_i5.Session>[]),
      ) as _i3.Future<List<_i5.Session>>);

  @override
  _i3.Future<List<_i2.ExerciseHistoryRecord>> getRecentExerciseHistory(
    String? exerciseName, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentExerciseHistory,
          [exerciseName],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i2.ExerciseHistoryRecord>>.value(
            <_i2.ExerciseHistoryRecord>[]),
      ) as _i3.Future<List<_i2.ExerciseHistoryRecord>>);

  @override
  _i3.Future<void> seedDummyWorkoutData() => (super.noSuchMethod(
        Invocation.method(
          #seedDummyWorkoutData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ExerciseLibraryRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseLibraryRepo extends _i1.Mock
    implements _i6.ExerciseLibraryRepo {
  MockExerciseLibraryRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, List<String>>> getLibrary() => (super.noSuchMethod(
        Invocation.method(
          #getLibrary,
          [],
        ),
        returnValue: _i3.Future<Map<String, List<String>>>.value(
            <String, List<String>>{}),
      ) as _i3.Future<Map<String, List<String>>>);

  @override
  _i3.Future<void> addExercise(
    String? bodyPart,
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExercise,
          [
            bodyPart,
            exerciseName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateExercise(
    String? oldBodyPart,
    String? oldExerciseName,
    String? newBodyPart,
    String? newExerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [
            oldBodyPart,
            oldExerciseName,
            newBodyPart,
            newExerciseName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteExercise(
    String? bodyPart,
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [
            bodyPart,
            exerciseName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i7.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  Iterable<E> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);

  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(Invocation.method(
        #keyAt,
        [index],
      ));

  @override
  _i3.Stream<_i7.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i3.Stream<_i7.BoxEvent>.empty(),
      ) as _i3.Stream<_i7.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i3.Future<Iterable<int>>.value(<int>[]),
      ) as _i3.Future<Iterable<int>>);

  @override
  _i3.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
